config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :purchases, only: [:index, :show]
  devise_for :users
  root "main#index"

  resources :cart, only: [:index] do
    member do
      post 'add', to: 'cart#add'
      patch 'add', to: 'cart#add'
      patch 'finish', to: 'cart#finish'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.buyer?
      can :buy, Product
    end

    if user.seller?
      can :manage, Product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, inverse_of: :carts
  has_many :lists, inverse_of: :cart, dependent: :destroy
  enum status: %i[open closed]

  def empty?
    lists.size.eql? 0
  end

  def items_size
    lists.to_a.sum { |list| list.quantity }
  end

  def total
    lists.to_a.sum { |list| list.total }
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :product, inverse_of: :lists
  belongs_to :cart, inverse_of: :lists

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, inverse_of: :products
  has_many :lists, inverse_of: :product, dependent: :destroy
  
  has_one_attached :picture
  has_rich_text :description

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :picture, presence: true
  validates :status, presence: true
  validates :description, presence: true

  enum status: %i[inactive active]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :last_name, presence: true

  has_many :products, inverse_of: :user, dependent: :destroy
  has_many :carts, inverse_of: :user, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[buyer seller]

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    attributes = [:name, :last_name, :email]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_product, only: %i[add]
  include CartConcern

  def index
  end

  def add
    @list = List.new(list_params)


    if current_list && @list.quantity > 0
      update
    elsif @list.quantity <= 0
      destroy
    else
      @list.cart = @cart
      @list.save!
    end

    render_partials
  end

  def update
    current_list.update(list_params)
  end

  def finish
    @cart.status = :closed
    @cart.save!
    close_cart

    render_partials
  end

  def destroy
    current_list.destroy
  end

  private
    def render_partials
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart}),
            turbo_stream.replace('cart_icon', partial: 'cart/cart_icon', locals: { cart: @cart  })
          ]
        end
      end
    end

    def current_list
      @cart.lists.find_by(product_id: @product.id)
    end

    def set_product
      @product = Product.find_by(id: list_params[:product_id])
    end

    def list_params
      params.require(:list).permit(:product_id, :cart_id, :quantity)
    end
end

app/controllers/concerns/cart_concern.rb
module CartConcern
  extend ActiveSupport::Concern  

  included do
    before_action :initialize_cart
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    return if @cart

    @cart = Cart.create(user: current_user)
    session[:cart_id] = @cart.id
  end

  def close_cart
    session[:cart_id] = nil
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  include CartConcern

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    authorize! :manage, @product
  end

  def edit
    authorize! :manage, @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :status, :quantity, :user_id, :picture, :description)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = current_user.carts.closed
  end

  def show
    @purchase = Cart.find(params[:id])
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cart/_action.html.slim
= simple_form_for(list, url: add_cart_path) do |f|
  .row
    .col-6
      = f.input :product_id, as: :hidden, input_html: { value: product.id }
      = f.input :quantity, label: false, input_html: { value: list.quantity }
    .col-4
      = f.button :submit, "Update", class: "btn btn-success mt-1"

app/views/cart/_cart.html.slim
= turbo_frame_tag "cart" do
  - unless @cart.empty? || @cart.closed?
    = render "cart/list"
    p
      | Total: 
      = @cart.total
    = link_to "Finish sale", finish_cart_path, class: "btn btn-lg btn-danger", data: { turbo_method: :patch }


  - else
    p
      | Your cart is empty

app/views/cart/_cart_icon.html.slim
= turbo_frame_tag "cart_icon" do
  = link_to cart_index_path,  class: "nav-item nav-link" do
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    span.top-0.start-100.translate-middle.badge.rounded-pill.bg-danger
      = @cart&.items_size || 0

app/views/cart/_list.html.slim
- @cart.lists.each do |list|
  - product = list.product
  .row
    .col-3
      = image_tag(product.picture, width: "100%")
    .col-8
      b = product.name
      br
      strong
        | Price:
      '
      = product.price
      - if can? :buy, product
        = render partial: "cart/action", locals: {product: product, list: list }
  hr

app/views/cart/index.html.slim
h1
  | Cart
hr
- if @cart.lists.count > 0
  = render "cart"
- else
  p
    | Your cart is empty

app/views/cart/show.html.slim
h1
  | Cart
hr
- if @cart.lists.count > 0
  = render "cart"
- else
  p
    | Your cart is empty

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-dark.navbar-expand-lg.bg-dark.fixed-top
  .container
    a.navbar-brand[href="#"]
      b Music Store
    button.navbar-toggler[type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar"]
      span.navbar-toggler-icon
    #offcanvasDarkNavbar.offcanvas.offcanvas-end.text-bg-dark[tabindex="-1" aria-labelledby="offcanvasDarkNavbarLabel"]
      .offcanvas-header
        h5#offcanvasDarkNavbarLabel.offcanvas-title
          | Menu
        button.btn-close.btn-close-white[type="button" data-bs-dismiss="offcanvas" aria-label="Close"]
      .offcanvas-body
        - if signed_in?
          ul.navbar-nav.justify-content-end.flex-grow-1.pe-3
            li.nav-item.active
              = link_to "Products", products_path, class: "nav-item nav-link"
            li.nav-item.dropdown
              a.nav-link.dropdown-toggle[href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"]
                = current_user.name.upcase 
              ul.dropdown-menu.dropdown-menu-dark
                li
                  = link_to "My purchases", purchases_path, class: "dropdown-item"
                li
                  = link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete }
            li.nav-item.active
              = render "cart/cart_icon"

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MusicStore
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render 'layouts/navbar'
    .container.mt-5
      = render "shared/flash"
      = yield

app/views/main/index.html.slim
.card.text-center
  .card-body.bg-light-gray
    .jumbotron
      h2
        | Welcome to the Music Store App
      p.mt-1
        a.btn.btn-primary[href="#" role="button"]
          | Sign up

app/views/products/_form.html.slim
= simple_form_for(@product) do |f|
  = render "devise/shared/error_messages", resource: @product
  .row
    .col-12
      = f.input :name
  .row
    .col-4
      = f.input :price
    .col-4
      = f.input :status, collection: Product.statuses.keys
    .col-4
      = f.input :quantity
  .row.mt-2
    .col-4
      = f.label :picture
      br
      = image_tag(@product.picture, width: 180, class: "rounded img-thumbnail mb-2") if @product.picture.attached?
      = f.file_field :picture
  .row.mt-2
    .col-12
      = f.label :description
      = f.rich_text_area :description
  br
  .form-actions.mt-1
    = f.button :submit, class: "btn btn-success"

app/views/products/_product.html.slim
.card.bg-light.text-dark
  = image_tag(product.picture, width: "200")
  .card-body
    h5.card-title
      = product.name
    p.card-text
      strong Price:
      '
      = product.price
    p
      strong Quantity:
      '
      = product.quantity
    p
      strong Status:
      '
      = product.status

app/views/products/edit.html.slim
.row
  .col-md-8.offset-md-2
    = link_to "Back to products", products_path, class: "btn btn-link"
    .card.text-left.mt-1
      .card-header
        h5.card-title.mt-1
          | Editing product
      .card-body
        == render "form", product: @product

app/views/products/index.html.slim
.row
  .col-10.text-left
    h1 Products
  .col-2.text-left
    - if can? :manage, Product
      = link_to "New product", new_product_path, class: "btn btn-success"
.row.mt-2
  - @products.each do |product|
    .col-md-3
      = link_to product, class: "text-d-none" do 
        == render product

app/views/products/new.html.slim
.row
  .col-md-8.offset-md-2
    = link_to "Back to products", products_path, class: "btn btn-link"
    .card.text-left.mt-1
      .card-header
        h5.card-title.mt-1
          | New product 
      .card-body
        == render "form", product: @product

app/views/products/show.html.slim
.row
  .col-md-8
    = link_to "Back to products", products_path, class: "btn btn-link"
    == render @product
    .card.card-body.mt-1
      strong Description:
      == @product.description
    - if can? :buy, @product
      = render partial: "cart/action", locals: { product: @product, list: List.new }
    - if can? :manage, @product
      .row.mt-1
        .col-3
          = link_to "Edit this product", edit_product_path(@product), class: "btn btn-info"
        .col-3
          = button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger"
  - if can? :buy, @product
    .col-md-4
      h5 Cart
      = render "cart/cart"

app/views/purchases/index.html.slim
.row
  .col-12.text-left
    h1 My purchases
.row.mt-1
  .col-12
    table.table
      thead
        tr
          th[scope="col"]
            | #
          th[scope="col"]
            | # Items
          th[scope="col"]
            | Total
          th[scope="col"]
            
      tbody
        - @purchases.each do |purchase|
          tr
            th[scope="row"]
              = purchase.id
            td
              = purchase.items_size
            td
              = purchase.total
            td
              = link_to "See details", purchase_path(purchase), class: "btn btn-primary" 

        

app/views/purchases/show.html.slim
.row
  .col-12.text-left
    h1 = "Purchase # #{@purchase.id}"
.row
  .col-12
    = link_to "Back to purchases", purchases_path, class: "btn btn-link"
    .card.card-body
      p
        strong Date:
        '
        = @purchase.updated_at
      table.table.mt2
        thead
          tr
            th[scope="col"]
              | Name
            th[scope="col"]
              | Unit price
            th[scope="col"]
              | Quantity
            th[scope="col"]
              | Total
            th[scope="col"]
              
        tbody
          - @purchase.lists.each do |list|
            tr
              th[scope="row"]
                = link_to list.product.name, list.product
              td
                = number_to_currency list.product.price
              td
                = list.quantity
              td
                = number_to_currency list.total
        tfoot
          tr
            td colspan="2"
            td 
              b = @purchase.items_size
            td 
              b = number_to_currency @purchase.total
              

app/views/shared/_flash.html.slim
- if flash[:alert].present?
  .alert.alert-warning.py-3.mt-2
    b = raw alert
- elsif flash[:notice].present?
  .alert.alert-success.py-3.mt-2 
    b = raw notice